openapi: 3.0.3
info:
  title: News API
  description: API service for fetching news articles from the GNews API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /articles:
    get:
      summary: Fetch N news articles
      parameters:
        - name: n
          in: query
          description: The number of articles to fetch (maximum 100)
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
        '400':
          description: Invalid request parameters
        '500':
          description: Internal server error
      example:
        summary: Fetch 5 news articles
        description: Returns an array of 5 news articles from the GNews API
        parameters:
          n: 5
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Article'
  /search:
    get:
      summary: Search news articles by query string
      parameters:
        - name: q
          in: query
          description: The search query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
        '400':
          description: Invalid request parameters
        '500':
          description: Internal server error
      example:
        summary: Search for technology news articles
        description: Returns an array of news articles related to technology
        parameters:
          q: technology
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Article'
  /{title}:
    get:
      summary: Find a news article with a specific title
      parameters:
        - name: title
          in: path
          description: The title of the article to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        '400':
          description: Invalid request parameters
        '500':
          description: Internal server error
      example:
        summary: Find an article with the title "Article Title"
        description: Returns a news article with the specified title
        parameters:
          title: Article Title
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Article'
components:
  schemas:
    Article:
      type: object
      properties:
        title:
          type: string
          description: The title of the article
        description:
          type: string
          description: A brief description of the article
        url:
          type: string
          description: The URL of the article
        image:
          type: string
          description: The URL of the article's image
        publishedAt:
          type: string
          format: date-time
          description: The date and time the article was published
          source:
          type: object
          properties:
          name:
          type: string
          description: The name of the news source
          url:
          type: string
          description: The URL of the news source
          required:
          - title
          - description
          - url
          - publishedAt
          - source
          securitySchemes:
          apiKey:
          type: apiKey
          in: query
          name: token
